# Generated by Django 4.2.5 on 2023-10-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='a', max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
